# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/memory_keeper_db
spring.datasource.username=memory_user
spring.datasource.password=dlsaktkd
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect

# SMS API configuration
sms.api.key=NCSPSQW1AKCTQIMW
sms.api.secret=5988IJB7K15UWUMLYZQXFUZKLPJOH6GC
sms.from.number=01034578792


