name: Maven Package and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package -Dspring.profiles.active=test

    - name: Prepare deployment package
      run: |
        mkdir -p deployment-package
        cp target/memory-keeper-0.0.1-SNAPSHOT.jar deployment-package/
        cp appspec.yml deployment-package/
        cp start.sh deployment-package/
        cd deployment-package
        zip -r ../deployment-package.zip .
        cd ..

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Upload to S3
      run: aws s3 cp deployment-package.zip s3://swtooltime-bucket/

    - name: Deploy to CodeDeploy
      run: |
        aws deploy create-deployment \
          --application-name ${{ secrets.CODEDEPLOY_APPLICATION_NAME }} \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --deployment-group-name ${{ secrets.CODEDEPLOY_DEPLOYMENT_GROUP_NAME }} \
          --s3-location bucket=swtooltime-bucket,key=deployment-package.zip,bundleType=zip \
          --region ap-northeast-2
      env:
        GITHUB_TOKEN: ${{ github.token }}
