name: Maven Package

on:
  push:
    branches:
      - main  # 주 브랜치에 푸시될 때만 실행되도록 설정

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2 # Change to your AWS region

    - name: Upload to S3
      run: aws s3 cp target/my-app-1.0-SNAPSHOT.jar s3://swtooltime-bucket/
      # Adjust the path to match your build artifact and S3 bucket details

    - name: Deploy to CodeDeploy
      run: |
        aws deploy create-deployment \
          --application-name ${{ secrets.CODEDEPLOY_APPLICATION_NAME }} \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --deployment-group-name ${{ secrets.CODEDEPLOY_DEPLOYMENT_GROUP_NAME }} \
          --s3-location bucket=swtooltime-bucket,key=my-app-1.0-SNAPSHOT.jar,bundleType=zip \
          --region ap-northeast-2
      env:
        GITHUB_TOKEN: ${{ github.token }}
